Rename multikey file to `multikey.conf`
So it doesn't clash with the multikey directory

diff --git a/hooks/pre-command b/hooks/pre-command
--- a/hooks/pre-command
+++ b/hooks/pre-command
@@ -14,20 +14,20 @@ s3_bucket="${BUILDKITE_PLUGIN_S3_SECRETS_BUCKET:-}"
 s3_bucket_prefix="${BUILDKITE_PLUGIN_S3_SECRETS_BUCKET_PREFIX:-$BUILDKITE_PIPELINE_SLUG}"
 
 if [[ -n "$s3_bucket" ]] ; then
-  echo "~~~ Downloading multikey from :s3: $s3_bucket" >&2;
+  echo "~~~ Downloading multikey.conf from :s3: $s3_bucket" >&2;
 
   if ! s3_bucket_exists "$s3_bucket" ; then
     echo "+++ :warning: Bucket $s3_bucket doesn't exist" >&2;
     exit 1
   fi
 
-  if s3_exists "$s3_bucket" "$s3_bucket_prefix/multikey" ; then
-    echo "Found multikey file, downloading" >&2;
-    if ! multikey=$(s3_download "${s3_bucket}" "$s3_bucket_prefix/multikey") ; then
-      echo "+++ :warning: Failed to download multikey file" >&2
+  if s3_exists "$s3_bucket" "$s3_bucket_prefix/multikey.conf" ; then
+    echo "Found multikey.conf file, downloading" >&2;
+    if ! multikey=$(s3_download "${s3_bucket}" "$s3_bucket_prefix/multikey.conf") ; then
+      echo "+++ :warning: Failed to download multikey.conf file" >&2
       exit 1
     fi
-    echo "Downloaded ${#multikey} bytes of multikey file"
+    echo "Downloaded ${#multikey} bytes of multikey.conf file"
     while IFS="," read -r provider repo; do
       keyname="${provider}-${repo//\//-}"
       key="${s3_bucket_prefix}/multikey/${keyname}"
